### ISSUE TITLE
`plot_backgroundlines()` needs to be a polygon

### ISSUE THREAD

**Issue by nickhaf** [nickhaf/eatPlot#268]
Die Background-linie soll eine Art Konfidenzintervall sein mit M +- SE an den vier Eckpunkten. 
Ich habe auf dem branch `backgorund_polyong` schonmal angefangen zu probieren und den data.frame für die Koordinaten erstellt, allerdings ist das noch ein bisschen durcheinander. @franikowsp :Hast du schon einmal mit `geom_polygons` gearbeitet? Ich glaube das Aussehen hängt von der Reihenfolge der Koordinaten ab, hast du da eine Idee, oder ein bisschen zeit das mal auszuprobieren?

Reprodizierbares Beispiel (noch etwas holprig):
```r
  dat <- data.frame(
    TR_BUNDESLAND = rep("wholeGroup", 2),
    year_start = c(2011, 2013),
    year_end = c(2013, 2016),
    est_noTrendStart_noComp_wholeGroup = c(10:11),
    est_noTrendEnd_noComp_wholeGroup = c(11:12),
    se_noTrendStart_noComp_wholeGroup = c(0.5, 1.2),
    se_noTrendEnd_noComp_wholeGroup = c(0.1, 0.9),
    years_Trend = c("20112013", "20132016")
  )

line_values <- c("est_noTrendStart_noComp_wholeGroup",  "est_noTrendEnd_noComp_wholeGroup")
line_se <- c("se_noTrendStart_noComp_wholeGroup",  "se_noTrendEnd_noComp_wholeGroup")


 colnames(dat) <- gsub("Start", ".Start", colnames(dat))
 line_values <- gsub("Start", ".Start", line_values)
 line_se <- gsub("Start", ".Start", line_se)
 colnames(dat) <- gsub("End", ".End", colnames(dat))
 line_values <- gsub("End", ".End", line_values)
 line_se <- gsub("End", ".End", line_se)

dat_long <- stats::reshape(
   dat,
   direction = "long",
   varying = c(line_values, line_se),
   sep = "."
 )

dat_long$y_pos <- dat_long$est_noTrend + dat_long$se_noTrend
dat_long$y_neg <- dat_long$est_noTrend - dat_long$se_noTrend
dat_long$id <- 1:nrow(dat_long)

dat_coords <- stats::reshape(
  dat_long,
  direction = "long",
  varying = c("y_pos", "y_neg"),
  sep = "_"
)

dat_coords <- dat_coords[order(dat_coords$y), ]
dat_coords <- dat_coords[order(dat_coords$est_noTrend), ]
dat_coords <- dat_coords[dat_coords$years_Trend == "20112013",]


## Kleiner Test:
ggplot2::ggplot() +
ggplot2::geom_polygon(data = dat_coords,
                      ggplot2::aes(
                        x = est_noTrend,
                        y = y,
                        group = .data$years_Trend
                      )) +
  ggplot2::facet_wrap(~years_Trend)
```

**Comment by franikowsp** [comment]
Habe ich schon einmal genutzt, glaube ich. Wo kriege ich z B. `line_values` her? Dann kann ich auch mal rumprobieren.

**Comment by nickhaf** [comment]
ah ja hoppla, war doch noch nicht ganz reprodzierbar, sollte es jetzt sein wenn du ggplot2 lädtst

**Comment by franikowsp** [comment]
Ich versuche mich die Tage gern mal daran! Welcher Datensatz wäre dafür geeignet zum Ausprobieren? Kann ich einfach den aus dem Test verwenden (`test-plot_background_lines.R`)?

**Comment by nickhaf** [comment]
Dankeschön! Ja der Test sollte ausreichen zum probieren.

**Comment by franikowsp** [comment]
Bin mir nicht ganz sicher: Soll das so aussehen oder braucht man `facet_wrap()`?

![image](https://user-images.githubusercontent.com/60889089/235947800-b16fe3e2-9415-48f1-9f48-dacac022b385.png)

**Comment by nickhaf** [comment]
Ja das sieht gut aus. Sollte auf alle Fälle auch mit facet_wrap funktionieren, am besten bei `aes(group = .data$years_Trend)` setzen, das ist die Gruppierungsvariable für die Facets.

**Comment by franikowsp** [comment]
Okay - aber das reicht, wenn das nach der Funktion eingeführt (also a) `ggplot()` + `plot_background_lines()` + `facet_wrap()` oder nur b) `ggplot() + plot_background_lines()`, wobei `facet_wrap()` dann bereits in `plot_background_lines()` enthalten ist) wird oder muss es auch in die Funktionsdefinition eingefügt werden? Habe mal die aktuelle Version (Variante a) ) gepusht, weiß aber noch nicht so ganz, ob das so richtig ist (irgendwie stimmt die Skalierung nicht, oder?).

**Comment by nickhaf** [comment]
Cool danke, schaue ich mir an! `facet_wrap()` wird global in gesetzt, muss also nicht in `plot_background_lines()` gesetzt werden. Dort würde ich wirklich nur die Gruppierungsvariable setzten, also eigentlich wie beim auskommentierten `geom_segment()` (alte Version, wo nur Linien gezogen werden), nur halt mit `geom_ribbon()`.
Ja Skalierung ist nicht richtig, `x` muss natürlich die Jahresspalte sein, und nicht `est_noTrend`. Habe ich schon falsch angefangen :D.

**Comment by franikowsp** [comment]
Ah, okay - macht Sinn. Aber welche Variable würde dann auf der x-Achse genau stehen? Da bin ich irgendwie gerade etwas verwirrt 🤯

**Comment by nickhaf** [comment]
Würde es functionieren wenn wir die Daten ins Longformat bringen, mit einer `year` - Spalte, zusammengeführt aus `year_start` und `year_end`?
