### ISSUE TITLE
Test `NA` removal in construct_label.

### ISSUE THREAD

**Issue by nickhaf** [nickhaf/eatPlot#423]
Please take a look at the `construct_label()` function. The documentation should include some minimal description of what the function does. The related test-file contains some simple tests for the general behavior of this function. Sadly, no Tests for dealing with `NA` values are included, which lead to some bug reports by users in the past :(.
There are some things which i think you could takle that would be really helpful:

- [x] Take a look at the documentation and try to understand what the function does. If you don't understand it, the documentation is bad, please let me know in that case. If you understand what the function does, but think the documentation could be improved, please do so. 
- [x] Add two examples to the documentation. One minimal one, and one that utilizes all of the functions arguments. Take a look at https://r-pkgs.org/man.html#sec-man-examples to see, how examples should be written. You can take the tests in the test file as inspiration. 
- [ ] Write either new test, or add to the old ones, to test if `NAs` are converted to empty strings as expected. Also add to the information on how the function deals with `NAs` to the documentation. 

Please let me know if you have any questions, need more input, are stuck etc. ...

**Comment by nickhaf** [comment]
@grewered : Hi, just wanted to remind you that this issue is still open (nothing urgent).

**Comment by grewered** [comment]
I know, last time I really looked at it i just didn't know how to come up with the examples, because I didn't fully understand the function and then I had other stuff to do. I think I'll lokk at it when I'm done with the Skalenhandbuch, but I didn't forget.

**Comment by grewered** [comment]
@nickhaf I wanted to create some new test for dealing with NA for this function, but the test checking for general function fails at the moment. Have you been working on this function? because I do have some understanding now of the function, but I don't think I could fix that easily.

**Comment by nickhaf** [comment]
> @nickhaf so can I close this issue then?

Yes please!
